baseURL = "https://rust-lang.github.io/compiler-team"
languageCode = "en-us"
title = "Rust Lang - Compiler Team"
theme = "book"
disablePathToLower = true

[params]
BookMenuBundle = '/menu'
enableGitInfo = true
