name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Install Hugo
        run: |
          HUGO_PATH="/tmp/hugo.deb"
          HUGO_VERSION="0.56.3"
          HUGO_SHA="4c8129b6f013d6b66c48446c681da8be20dfc504e5119c9f28a0b7115b9cb53e"
          wget -O ${HUGO_PATH} https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
          echo "${HUGO_SHA}  ${HUGO_PATH}" | sha256sum --check && \
          sudo dpkg -i ${HUGO_PATH} && \
          hugo version
      - name: Minify HTML
        run: hugo --minify
      - name: Deploy
        run: |
          deploy_dir=public
          # Ensure GitHub doesn't mess around with the uploaded file.
          # Without the file, for example, files with an underscore in the name won't be
          # included in the pages.
          touch "${deploy_dir}/.nojekyll"
          # Push the website to GitHub pages
          cd "${deploy_dir}"
          rm -rf .git
          git init
          git config user.name "Deploy from CI"
          git config user.email ""
          git add .
          git commit -m "Deploy ${GITHUB_SHA} to gh-pages"
          git push -f "https://x-token:${github_token}@github.com/${GITHUB_REPOSITORY}" master:gh-pages
        env:
         - github_token: ${{ secrets.GITHUB_TOKEN }}
